# Generated by Django 2.2.12 on 2021-10-13 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('citizenship', models.CharField(max_length=5)),
                ('sex', models.CharField(max_length=5)),
                ('personal_no', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('signature', models.TextField(max_length=100)),
                ('card_no', models.CharField(max_length=9)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('date_of_issue', models.DateTimeField(default=django.utils.timezone.now)),
                ('issuing_authority', models.TextField(max_length=400)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
