# Generated by Django 2.2.12 on 2021-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211013_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
