# Generated by Django 2.2.12 on 2021-10-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_info_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
