# Generated by Django 2.2.12 on 2021-10-15 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211015_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='personal_no',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
