# Generated by Django 2.2.12 on 2021-10-15 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211015_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='personal_no',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
