# Generated by Django 2.2.12 on 2021-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211015_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='citizenship',
            field=models.CharField(default='GEO', max_length=3),
        ),
    ]
