# Generated by Django 2.2.12 on 2021-10-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20211015_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('FM', 'FM')], max_length=10),
        ),
    ]
