# Generated by Django 2.2.12 on 2021-10-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211015_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, default='media/images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
