# Generated by Django 2.2.12 on 2021-10-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20211015_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='sex',
            new_name='gen',
        ),
    ]
